project:
  type: website

website:
  title: "Course Notes"
  site-url: "https://sihanwei.org/notes/"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
  sidebar:
    style: floating
    search: true
    contents: auto

format:
  html:
    theme: 
      light: litera
      dark: darkly
    toc: true
    css: style.css
    number-sections: true
    author:
      - name: Sihan Wei
        email: me@sihanwei.org
        affiliation: University of Delaware




