project:
  type: website

website:
  title: "Course Notes"
  site-url: "https://sihanwei.org"
  site-path: "/notes"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
  sidebar:
    style: floating
    search: true
    contents: 
      - "---"
      - section: courses/measure-theory/index.qmd
        contents: 
          - courses/measure-theory/01-intro.qmd
      - "---"
      - section: courses/probability-theory/index.qmd
      - "---"
      - section: courses/functional-analysis/index.qmd

format:
  html:
    theme: 
      light: litera
      dark: darkly
    toc: true
    css: style.css
    number-sections: true
    author:
      - name: Sihan Wei
        email: me@sihanwei.org
        affiliation: University of Delaware




