project:
  type: website

website:
  title: "Course Notes"


  navbar:
    left:
      - text: "Home"
        href: index.qmd

  sidebar:
    search: true
    contents:
    - section: measure-theory/index.qmd
      contents:
        - measure-theory/01-intro.qmd
    - section: probability-theory/index.qmd
    - section: functional-analysis/index.qmd

format:
  html:
    theme:
      light: litera
      dark: darkly
    toc: true
    css: style.css
    number-sections: true
    author:
      - name: Sihan Wei
        email: me@sihanwei.org
        affiliation: University of Delaware