project:
  type: website

website:
  title: "Course Notes"
  site-url: "https://sihanwei.org/notes/"

navbar:
  left:
    - text: "Home"
      href: index.qmd

sidebar:
  style: floating
  search: true
  contents:
    - index.qmd
    - section: "Measure Theory"
      href: "/notes/courses/measure-theory/index.qmd"
      contents:
        - "/notes/courses/measure-theory/01-intro.qmd"
    - section: "Probability Theory"
      href: "/notes/courses/probability-theory/index.qmd"
    - section: "Functional Analysis"
      href: "/notes/courses/functional-analysis/index.qmd"

format:
  html:
    theme:
      light: litera
      dark: darkly
    toc: true
    css: style.css
    number-sections: true
    author:
      - name: Sihan Wei
        email: me@sihanwei.org
        affiliation: University of Delaware